### ISSUE TITLE
why it's not sending to my email ?!

### ISSUE THREAD

**Issue by Arabiabitz** [aron-tn/Smtp-cracker#4]
Actually i used this tool and it's awesome .
it was sending the results to my email but it's suddenly stopped sending the results to my email .
any advice ?

**Comment by Aron-Tn** [comment]
Hi !
i have update it these is fixed version :3
https://github.com/aron-tn/SMTP.Cracker
Thank You !

Le ven. 5 juil. 2019 à 03:39, Arabiabitz <notifications@github.com> a
écrit :

**Comment by Cacatel** [comment]
The link u provided is not working, also the updated V2 is still not working ..
